services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - USE_MYSQL=True
      - MYSQL_DATABASE=yourdbname
      - MYSQL_USER=yourdbuser
      - MYSQL_PASSWORD=yourdbpassword
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: yourdbname
      MYSQL_USER: yourdbuser
      MYSQL_PASSWORD: yourdbpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
