# Generated by Django 4.2.4 on 2025-01-22 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_webpage_content2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webpage",
            name="content2",
        ),
    ]
