# Generated by Django 4.2.4 on 2025-01-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_remove_webpage_content2"),
    ]

    operations = [
        migrations.AddField(
            model_name="webpage",
            name="content2",
            field=models.TextField(blank=True, null=True),
        ),
    ]
