# Generated by Django 4.2.4 on 2025-01-22 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_webpage_content2"),
    ]

    operations = [
        migrations.AddField(
            model_name="webpage",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
