# Generated by Django 4.2.4 on 2025-01-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_webpage_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="content",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="image",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
