# Generated by Django 4.2.4 on 2025-01-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_alter_content_options_alter_image_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webpage",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="app/images/tintuc/"
            ),
        ),
    ]
