# Generated by Django 4.2.4 on 2025-01-22 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_webpage_image2"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="app/images/tintuc/")),
                ("caption", models.CharField(blank=True, max_length=255, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "webpage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images2",
                        to="app.webpage",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
