# Generated by Django 4.2.4 on 2025-01-22 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_content2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webpage",
            name="content",
        ),
        migrations.RemoveField(
            model_name="webpage",
            name="content2",
        ),
    ]
