# Generated by Django 4.2.4 on 2025-01-22 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_remove_webpage_content_remove_webpage_content2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webpage",
            name="image2",
        ),
    ]
