# Generated by Django 4.2.4 on 2025-01-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_remove_webpage_image2"),
    ]

    operations = [
        migrations.AddField(
            model_name="webpage",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="app/images/tintuc/"
            ),
        ),
    ]
