# Generated by Django 4.2.4 on 2025-01-22 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_webpage_image2"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "webpage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents3",
                        to="app.webpage",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
