# Generated by Django 4.2.4 on 2025-01-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_content3"),
    ]

    operations = [
        migrations.AddField(
            model_name="webpage",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
