# Generated by Django 4.2.4 on 2025-01-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_alter_webpage_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webpage",
            name="category",
            field=models.CharField(
                choices=[("tin-tuc-su-kien", "Tin Tức"), ("other", "Khác")],
                default="other",
                max_length=50,
            ),
        ),
    ]
