# Generated by Django 4.2.4 on 2025-01-27 18:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("app", "0017_alter_webpage_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebPage2tb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[("thong-bao-moi", "Thông Báo"), ("other", "Khác")],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="app/images/tintuc/"
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                ("video_url", models.URLField(blank=True, null=True)),
                (
                    "image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="app/images/tintuc/"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="content",
            name="webpage2tb",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="app.webpage2tb",
            ),
        ),
        migrations.AddField(
            model_name="content2",
            name="webpage2tb",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents2",
                to="app.webpage2tb",
            ),
        ),
        migrations.AddField(
            model_name="content3",
            name="webpage2tb",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents3",
                to="app.webpage2tb",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="webpage2tb",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="app.webpage2tb",
            ),
        ),
        migrations.AddField(
            model_name="image2",
            name="webpage2tb",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images2",
                to="app.webpage2tb",
            ),
        ),
    ]
