# Generated by Django 4.2.4 on 2025-01-27 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0018_webpage2tb_content_webpage2tb_content2_webpage2tb_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="webpage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="app.webpage",
            ),
        ),
        migrations.AlterField(
            model_name="content2",
            name="webpage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents2",
                to="app.webpage",
            ),
        ),
        migrations.AlterField(
            model_name="content3",
            name="webpage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents3",
                to="app.webpage",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="webpage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="app.webpage",
            ),
        ),
        migrations.AlterField(
            model_name="image2",
            name="webpage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images2",
                to="app.webpage",
            ),
        ),
    ]
