# Generated by Django 5.1.4 on 2025-02-05 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
