# Generated by Django 5.1.5 on 2025-02-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0026_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                default="example@example.com", max_length=254, unique=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="hovaten",
            field=models.CharField(default="Default Name", max_length=255),
        ),
    ]
