# Generated by Django 5.1.4 on 2025-02-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_webpage_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=120)),
                ('user', models.CharField(max_length=80)),
                ('topic', models.CharField(max_length=120)),
                ('request_title', models.CharField(max_length=200)),
                ('request_content', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('response', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
