# Generated by Django 5.1.4 on 2025-02-07 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_supportrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 2, 7, 21, 17, 28, 996494, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
