# Generated by Django 5.1.4 on 2025-02-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0032_remove_customuser_groups_remove_customuser_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportrequest",
            name="response_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supportrequest",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed")],
                default="open",
                max_length=10,
            ),
        ),
    ]
