# Generated by Django 5.1.4 on 2025-02-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_chatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("address", models.CharField(max_length=100)),
                ("school", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="TuitionDebt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.CharField(max_length=255)),
                ("class_code", models.CharField(max_length=50)),
                ("subject_name", models.CharField(max_length=255)),
                ("credit", models.IntegerField()),
                ("tuition_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "registration_status",
                    models.CharField(default="Đăng ký mới", max_length=100),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "deduction_plus",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "deduction_minus",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="webpage",
            name="category",
            field=models.CharField(
                choices=[("tin-tuc-su-kien", "Tin Tức"), ("other", "Khác")],
                default="other",
                max_length=50,
            ),
        ),
    ]
