# Generated by Django 5.1.4 on 2025-02-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0037_course_record_tuitiondebt_alter_webpage_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webpage",
            name="category",
            field=models.CharField(
                choices=[
                    ("tin-tuc-su-kien", "Tin Tức"),
                    ("tuyen-sinh", "Tuyển Sinh"),
                    ("other", "Khác"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
