# Generated by Django 5.1.4 on 2025-02-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0039_dashboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="webpage",
            name="content2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="webpage",
            name="content3",
            field=models.TextField(blank=True, null=True),
        ),
    ]
