# Generated by Django 5.1.4 on 2025-02-14 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0040_webpage_content2_webpage_content3"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webpage",
            name="content2",
        ),
        migrations.RemoveField(
            model_name="webpage",
            name="content3",
        ),
    ]
