# Generated by Django 5.1.4 on 2025-02-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0041_remove_webpage_content2_remove_webpage_content3"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(auto_now_add=True)),
                ("total_webpages", models.IntegerField(default=0)),
                ("total_webpages2tb", models.IntegerField(default=0)),
                ("total_support_requests", models.IntegerField(default=0)),
                ("total_articles", models.IntegerField(default=0)),
            ],
        ),
    ]
