# Generated by Django 5.1.4 on 2025-02-14 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0042_report"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Dashboard",
        ),
    ]
