# Generated by Django 5.1.4 on 2025-02-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0043_delete_dashboard"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("dob", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                ("school", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=50)),
                ("facebook", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
