# Generated by Django 5.1.4 on 2025-02-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0044_studentregistration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentregistration",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
