# Generated by Django 5.1.4 on 2025-02-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0045_alter_studentregistration_dob"),
    ]

    operations = [
        migrations.CreateModel(
            name="GvLogin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("hovaten", models.CharField(default="Default Name", max_length=255)),
                (
                    "email",
                    models.EmailField(
                        default="example@example.com", max_length=254, unique=True
                    ),
                ),
            ],
        ),
    ]
